CREATE TABLE IF NOT EXISTS USERS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
)
    ENGINE  = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS ROLES (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),

    UNIQUE (USER_ID, ROLE_ID)
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8
;

CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(45) NOT NULL
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME varchar(45) NOT NULL,
    LAST_NAME varchar(45) DEFAULT NULL,
    DATE_OF_BIRTH date DEFAULT NULL,
    SALARY int(11) DEFAULT NULL,
    START_DATE date DEFAULT NULL,
    DEPARTMENT int(11) DEFAULT NULL
)
    ENGINE = InnoDB DEFAULT CHARSET = utf8;

